  <script type="text/javascript">
    function toggleHide(which) {
      console.log();
      var focus = document.getElementsByClassName(which)[0];
      if (focus.style.display === "block") {
        focus.style.display = "none";
      } else {
        focus.style.display = "block";
      }
    }
  </script>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
  <script src="js/menu-highlighter.js"></script>
